services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=admin
      - DATABASE_NAME=hicut_db
    depends_on:
      - db
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - hicut_network

  db:
    image: postgres:latest
    container_name: hicut_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hicut_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hicut_network
    restart: unless-stopped
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: hicut_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8082:80"
    depends_on:
      - db
    networks:
      - hicut_network
    restart: unless-stopped

networks:
  hicut_network:
    driver: bridge

volumes:
  postgres_data: